name: Our first python CI!
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  My-first-CI:
  
    runs-on: [ubuntu-latest, windows-latest, macos-latest] 
    
    steps: 
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r /src/requirements.txt
    - name: Lint with Ruff
      run: |
        python -m ruff lint
    - name: Test with pytest
      run: |
        python -m pytest
